import type { Metadata } from "next";
import "@/src/styles/globals.css";
import { Providers } from "../lib/Providers";


export const metadata: Metadata = {
  title: "TrendTweaks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}>
      <Providers>
      {children}
      </Providers>
      
      </body>
    </html>
  );
}